version: '4.4'

services:
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://vikingpanther72:Test%40123@companydb.kq9msd1.mongodb.net/?retryWrites=true&w=majority&appName=CompanyDB
      - NODE_ENV=production
    networks:
      - webnet

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - webnet

  admin:
    build: ./admin
    container_name: admin
    restart: unless-stopped
    env_file: ./admin/.env
    volumes:
      - ./admin:/app
      - admin_node_modules:/app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - server
      - client
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - admin
      - server
    networks:
      - webnet

volumes:
  server_node_modules:
  client_node_modules:
  admin_node_modules:

networks:
  webnet:
    driver: bridge