version: '4.4'

services:
  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://vikingpanther72:Test%40123@companydb.kq9msd1.mongodb.net/?retryWrites=true&w=majority&appName=CompanyDB
      - NODE_ENV=production

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server

  admin:
    build: ./admin
    container_name: admin
    restart: unless-stopped
    env_file: ./admin/.env
    volumes:
      - ./admin:/app
      - admin_node_modules:/app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - server
      - client

volumes:
  server_node_modules:
  client_node_modules:
  admin_node_modules: